tabela={
  "H": {"nome": "Hidrogênio", "massa_atomica": 1, "massa": 1.008},
  "HE": {"nome": "Hélio", "massa_atomica": 2, "massa": 4.0026},
  "LI": {"nome": "Lítio", "massa_atomica": 3, "massa": 6.94},
  "BE": {"nome": "Berílio", "massa_atomica": 4, "massa": 9.0122},
  "B": {"nome": "Boro", "massa_atomica": 5, "massa": 10.81},
  "C": {"nome": "Carbono", "massa_atomica": 6, "massa": 12.011},
  "N": {"nome": "Nitrogênio", "massa_atomica": 7, "massa": 14.007},
  "O": {"nome": "Oxigênio", "massa_atomica": 8, "massa": 15.999},
  "F": {"nome": "Flúor", "massa_atomica": 9, "massa": 18.998},
  "NE": {"nome": "Neônio", "massa_atomica": 10, "massa": 20.18},
  "NA": {"nome": "Sódio", "massa_atomica": 11, "massa": 22.99},
  "MG": {"nome": "Magnésio", "massa_atomica": 12, "massa": 24.305},
  "AL": {"nome": "Alumínio", "massa_atomica": 13, "massa": 26.982},
  "SI": {"nome": "Silício", "massa_atomica": 14, "massa": 28.085},
  "P": {"nome": "Fósforo", "massa_atomica": 15, "massa": 30.974},
  "S": {"nome": "Enxofre", "massa_atomica": 16, "massa": 32.06},
  "CL": {"nome": "Cloro", "massa_atomica": 17, "massa": 35.45},
  "AR": {"nome": "Argônio", "massa_atomica": 18, "massa": 39.95},
  "K": {"nome": "Potássio", "massa_atomica": 19, "massa": 39.098},
  "CA": {"nome": "Cálcio", "massa_atomica": 20, "massa": 40.078},
  "SC": {"nome": "Escândio", "massa_atomica": 21, "massa": 44.956},
  "TI": {"nome": "Titânio", "massa_atomica": 22, "massa": 47.867},
  "V": {"nome": "Vanádio", "massa_atomica": 23, "massa": 50.942},
  "CR": {"nome": "Cromo", "massa_atomica": 24, "massa": 51.996},
  "MN": {"nome": "Manganês", "massa_atomica": 25, "massa": 54.938},
  "FE": {"nome": "Ferro", "massa_atomica": 26, "massa": 55.938},
  "CO": {"nome": "Cobalto", "massa_atomica": 27, "massa": 58.933},
  "NI": {"nome": "Níquel", "massa_atomica": 28, "massa": 58.693},
  "CU": {"nome": "Cobre", "massa_atomica": 29, "massa": 63.546},
  "ZN": {"nome": "Zinco", "massa_atomica": 30, "massa": 65.38},
  "GA": {"nome": "Gálio", "massa_atomica": 31, "massa": 69.723},
  "GE": {"nome": "Germânio", "massa_atomica": 32, "massa": 72.63},
  "AS": {"nome": "Arsênio", "massa_atomica": 33, "massa": 74.922},
  "SE": {"nome": "Selênio", "massa_atomica": 34, "massa": 78.971},
  "BR": {"nome": "Bromo", "massa_atomica": 35, "massa": 79.904},
  "KR": {"nome": "Criptônio", "massa_atomica": 36, "massa": 83.798},
  "RB": {"nome": "Rubídio", "massa_atomica": 37, "massa": 85.468},
  "SR": {"nome": "Estrôncio", "massa_atomica": 38, "massa": 87.62},
  "Y": {"nome": "Ítrio", "massa_atomica": 39, "massa": 88.906},
  "ZR": {"nome": "Zircônio", "massa_atomica": 40, "massa": 91.224},
  "NB": {"nome": "Nióbio", "massa_atomica": 41, "massa": 92.906},
  "MO": {"nome": "Molibdênio", "massa_atomica": 42, "massa": 95.95},
  "TC": {"nome": "Tecnécio", "massa_atomica": 43, "massa": 98},
  "RU": {"nome": "Rutênio", "massa_atomica": 44, "massa": 101.07},
  "RH": {"nome": "Ródio", "massa_atomica": 45, "massa": 102.91},
  "PD": {"nome": "Paládio", "massa_atomica": 46, "massa": 106.42},
  "AG": {"nome": "Prata", "massa_atomica": 47, "massa": 107.87},
  "CD": {"nome": "Cádmio", "massa_atomica": 48, "massa": 112.41},
  "IN": {"nome": "Índio", "massa_atomica": 49, "massa": 114.82},
  "SN": {"nome": "Estanho", "massa_atomica": 50, "massa": 118.71},
  "SB": {"nome": "Antimônio", "massa_atomica": 51, "massa": 121.76},
  "TE": {"nome": "Telúrio", "massa_atomica": 52, "massa": 127.6},
  "I": {"nome": "Iodo", "massa_atomica": 53, "massa": 126.9},
  "XE": {"nome": "Xenônio", "massa_atomica": 54, "massa": 131.29},
  "CS": {"nome": "Césio", "massa_atomica": 55, "massa": 132.91},
  "BA": {"nome": "Bário", "massa_atomica": 56, "massa": 137.33},
  "LA": {"nome": "Lantânio", "massa_atomica": 57, "massa": 138.91},
  "CE": {"nome": "Cério", "massa_atomica": 58, "massa": 140.12},
  "PR": {"nome": "Praseodímo", "massa_atomica": 59, "massa": 140.91},
  "ND": {"nome": "Neodímio", "massa_atomica": 60, "massa": 144.24},
  "PM": {"nome": "Promécio", "massa_atomica": 61, "massa": 145},
  "SM": {"nome": "Samário", "massa_atomica": 62, "massa": 150.36},
  "EU": {"nome": "Európio", "massa_atomica": 63, "massa": 151.96},
  "GD": {"nome": "Gadolínio", "massa_atomica": 64, "massa": 157.25},
  "TB": {"nome": "Térbio", "massa_atomica": 65, "massa": 158.93},
  "DY": {"nome": "Disprósio", "massa_atomica": 66, "massa": 162.5},
  "HO": {"nome": "Hólmio", "massa_atomica": 67, "massa": 164.93},
  "ER": {"nome": "Érbio", "massa_atomica": 68, "massa": 167.26},
  "TM": {"nome": "Túlio", "massa_atomica": 69, "massa": 168.93},
  "YB": {"nome": "Itérbio", "massa_atomica": 70, "massa": 173.05},
  "LU": {"nome": "Lutécio", "massa_atomica": 71, "massa": 174.97},
  "HF": {"nome": "Háfnio", "massa_atomica": 72, "massa": 178.49},
  "TA": {"nome": "Tântalo", "massa_atomica": 73, "massa": 180.95},
  "W": {"nome": "Tungstênio", "massa_atomica": 74, "massa": 183.84},
  "RE": {"nome": "Rênio", "massa_atomica": 75, "massa": 186.21},
  "OS": {"nome": "Ósmio", "massa_atomica": 76, "massa": 190.23},
  "IR": {"nome": "Irídio", "massa_atomica": 77, "massa": 192.22},
  "PT": {"nome": "Platina", "massa_atomica": 78, "massa": 195.08},
  "AU": {"nome": "Ouro", "massa_atomica": 79, "massa": 196.97},
  "HG": {"nome": "Mercúrio", "massa_atomica": 80, "massa": 200.59},
  "TL": {"nome": "Tálio", "massa_atomica": 81, "massa": 204.38},
  "PB": {"nome": "Chumbo", "massa_atomica": 82, "massa": 207.2},
  "BI": {"nome": "Bismuto", "massa_atomica": 83, "massa": 208.98},
  "PO": {"nome": "Polônio", "massa_atomica": 84, "massa": 209},
  "AT": {"nome": "Astato", "massa_atomica": 85, "massa": 210},
  "RN": {"nome": "Radônio", "massa_atomica": 86, "massa": 222},
  "FR": {"nome": "Frâncio", "massa_atomica": 87, "massa": 223},
  "RA": {"nome": "Rádio", "massa_atomica": 88, "massa": 226},
  "AC": {"nome": "Actínio", "massa_atomica": 89, "massa": 227},
  "TH": {"nome": "Tório", "massa_atomica": 90, "massa": 232.04},
  "PA": {"nome": "Protactínio", "massa_atomica": 91, "massa": 231.04},
  "U": {"nome": "Urânio", "massa_atomica": 92, "massa": 238.03},
  "NP": {"nome": "Netúnio", "massa_atomica": 93, "massa": 237},
  "PU": {"nome": "Plutônio", "massa_atomica": 94, "massa": 244},
  "AM": {"nome": "Amerício", "massa_atomica": 95, "massa": 243},
  "CM": {"nome": "Cúrio", "massa_atomica": 96, "massa": 247},
  "BK": {"nome": "Berquélio", "massa_atomica": 97, "massa": 247},
  "CF": {"nome": "Califórnio", "massa_atomica": 98, "massa": 251},
  "ES": {"nome": "Einstênio", "massa_atomica": 99, "massa": 252},
  "FM": {"nome": "Férmio", "massa_atomica": 100, "massa": 257},
  "MD": {"nome": "Mendelévio", "massa_atomica": 101, "massa": 258},
  "NO": {"nome": "Nobélio", "massa_atomica": 102, "massa": 259},
  "LR": {"nome": "Laurêncio", "massa_atomica": 103, "massa": 266},
  "RF": {"nome": "Rutherfórdio", "massa_atomica": 104, "massa": 267},
  "DB": {"nome": "Dúbnio", "massa_atomica": 105, "massa": 268},
  "SG": {"nome": "Seabórgio", "massa_atomica": 106, "massa": 269},
  "BH": {"nome": "Bóhrio", "massa_atomica": 107, "massa": 270},
  "HS": {"nome": "Hássio", "massa_atomica": 108, "massa": 277},
  "MT": {"nome": "Meitnério", "massa_atomica": 109, "massa": 278},
  "DS": {"nome": "Darmstádio", "massa_atomica": 110, "massa": 281},
  "RG": {"nome": "Roentgênio", "massa_atomica": 111, "massa": 282},
  "CN": {"nome": "Copernício", "massa_atomica": 112, "massa": 285},
  "NH": {"nome": "Nihônio", "massa_atomica": 113, "massa": 286},
  "FL": {"nome": "Fleróvio", "massa_atomica": 114, "massa": 289},
  "MC": {"nome": "Moscóvio", "massa_atomica": 115, "massa": 290},
  "LV": {"nome": "Livermório", "massa_atomica": 116, "massa": 293},
  "TS": {"nome": "Tenessino", "massa_atomica": 117, "massa": 294},
  "OG": {"nome": "Oganessônio", "massa_atomica": 118, "massa": 294}
  }
while True:
    op=int(input("\n1.buscar elemento\n2.sair"))
    if op==1:
        filtro=int(input("digite o número atômico do elemento:\n"))
        for elemento in tabela:
            if tabela[elemento]["numeroAtm"]==filtro:
               print(f"elemento encontrado:{elemento}-{tabela[elemento]}")
            
    elif op==2:
        print("você saiu")
        break 
    else:
        print ("comando inválido")
        break           
